name = "cda-transparencia"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
[env.production]
name = "cda-transparencia"

# Build configuration is handled by build.sh
# Output directory for deployment
pages_build_output_dir = "frontend/dist"
