name = "cda-transparencia"
compatibility_date = "2024-01-01"
main = "worker.js"

# Environment variables
[vars]
ENVIRONMENT = "production"
DEBUG = "false"

# Define routes for the worker
routes = [
  "https://cda-transparencia.franco-longstaff.workers.dev/*",
  "https://cda-transparencia.org/api/*"
]

# CORS configuration
[cloudflare]
# Enable CORS headers for all responses
cors = true

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "transparency_portal_analytics"

# Compatibility flags for latest features
[triggers]
crons = []

# Production environment configuration
[env.production]
# Production environment-specific variables
[env.production.vars]
ENVIRONMENT = "production"
DEBUG = "false"

# Production Analytics Engine binding  
[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "transparency_portal_analytics"