from setuptools import setup, find_packages

setup(
    name="transparency-portal",
    version="1.0.0",
    author="Transparency Research Team",
    author_email="transparency@carmendeareco.gob.ar",
    description="Carmen de Areco Transparency Portal",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/carmendeareco/transparency-portal",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
    install_requires=[
        "psycopg2-binary>=2.9.0",
        "PyPDF2>=3.0.0",
        "requests>=2.28.0",
        "beautifulsoup4>=4.11.0",
        "lxml>=4.9.0",
        "pandas>=1.5.0",
        "numpy>=1.23.0",
        "openpyxl>=3.0.0",
        "xlsxwriter>=3.0.0",
        "pdfplumber>=0.7.0",
        "Flask>=2.2.0",
        "gunicorn>=20.1.0",
        "python-dateutil>=2.8.0",
        "click>=8.0.0",
        "waybackpy>=3.0.0",
        "aiohttp>=3.8.0",
        "selenium>=4.0.0",
    ],
    entry_points={
        "console_scripts": [
            "transparency-portal=transparency_portal.cli:cli",
        ],
    },
)