name: Deploy to Cloudflare Pages
# DISABLED: Cloudflare now pulls from GitHub Pages automatically

on:
  # Disabled automatic triggers - Cloudflare uses GitHub Pages as source
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          # Install Python dependencies
          pip install -r requirements_complete.txt
          
          # Install frontend dependencies
          cd frontend
          npm ci

      - name: Build
        run: |
          # Run data preprocessing
          python scripts/generate-data-index.py
          python scripts/transform-processed-data.py
          
          # Build frontend
          cd frontend
          npm run build
        env:
          NODE_ENV: production

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cda-transparencia
          directory: frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}