name: Deploy to Cloudflare Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      # Install wrangler for Cloudflare Pages deployment
      - name: Install wrangler
        run: npm install -g wrangler
        
      # Install frontend dependencies
      - run: cd frontend && npm ci
      
      # Build the frontend with GitHub Pages configuration
      - run: cd frontend && npm run build:github
      
      # Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cda-transparencia
          directory: ./frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}