name: Deploy Transparency Portal to GitHub Pages

on:
  # Run on pushes to main branch - TRIGGERED BY COMMIT
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Run weekly on Sundays at 2 AM UTC to refresh data
  schedule:
    - cron: "0 2 * * 0"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: |
          pip install -r requirements_complete.txt
          
      - name: Run data preprocessing scripts
        run: |
          node scripts/generate-data-index.js
          node scripts/transform-processed-data.js
          
      - name: Build frontend for production (custom domain)
        run: |
          cd frontend
          npm run build:production
        env:
          VITE_API_URL: "https://api.cda-transparencia.org"
          VITE_USE_API: "true"
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: 'frontend/dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Verify deployment
        run: |
          echo "Site deployed to: ${{ steps.deployment.outputs.page_url }}"