name: Test Deployment

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd frontend && npm install
        cd ../backend && npm install
        pip install -r requirements.txt
        
    - name: Test build
      run: |
        cd frontend
        npm run build
        echo "Frontend build successful"
        
    - name: Test API
      run: |
        cd backend
        npm start & 
        sleep 10
        curl -s http://localhost:3001/api/health
        echo "API test completed"